name: test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    strategy:
      matrix:
        go-version: ['stable','oldstable']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: checkout
        uses: actions/checkout@v4
      - name: test (race detector)
        run: go test -race ./...
      - name: test (verbose)
        run: go test -v ./...
